story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('story1/', views.index, name='index'),

]

story3/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
app_name = 'story3'

urlpatterns = [
    path('', views.index, name='index'),
    path('Contact/', views.Contact, name='Contact'),
    path('tambahmatkul/', views.add_matkul, name='tambahmatkul'),
    path('daftarmatkul/', views.daftar_matkul, name='daftarmatkul'),
    path('delete/<str:pk>', views.delete, name='delete'),
    path('ikutkegiatan/', views.ikut_kegiatan, name='ikutkegiatan'),
    path('daftarkegiatan/', views.daftar_kegiatan, name='daftarkegiatan'),
    path('tambahkegiatan/', views.tambah_kegiatan, name='tambahkegiatan'),
    path('deletekegiatan/<str:pk>', views.deletekegiatan, name='deletekegiatan'),
    path('About/', views.about, name='about'),
    path('Story8/', views.story8, name='story8'),
    path('data/', views.olahdata, name='data'),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', LogoutView.as_view(next_page='story3:login'), name="logout")
    ]

storyarik/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story3.urls')),
    path('', include('story1.urls'))
]

story1/models.py
from django.db import models

# Create your models here.

story3/models.py
from django.db import models

# Create your models here.

class Matkul(models.Model):
    nama = models.CharField(max_length=50)
    dosen = models.CharField(max_length=50)
    sks = models.IntegerField()
    deskripsi = models.CharField(max_length=100)
    tahun = models.CharField(max_length=10)
    ruangan = models.CharField(max_length=100)

    def __str__(self):
        return self.nama

class Kegiatan(models.Model):
    nama = models.CharField(max_length=50, null=True)
    
    def __str__(self):
        return self.nama


class Peserta(models.Model):
    nama = models.CharField(max_length=50, null=True)
    kegiatan = models.ForeignKey(Kegiatan, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.nama

    

story3/forms.py
from django import forms

from .models import Matkul, Kegiatan, Peserta

class FormMatkul(forms.ModelForm):

    class Meta:
        model = Matkul
        fields = ['nama', 'dosen', 'sks', 'deskripsi', 'tahun', 'ruangan']

class FormPeserta(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = ['nama', 'kegiatan']

class FormKegiatan(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = ['nama']

story1/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'story1.html')

story3/views.py
from django.shortcuts import render, redirect
from .forms import FormMatkul, FormKegiatan, FormPeserta
from .models import Matkul, Kegiatan, Peserta
from django.http import HttpResponse
from django.http import JsonResponse
import json
import requests
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request, 'profile.html')

def Contact(request):
    return render(request, 'Contact.html')

def add_matkul(request):
    daftar = Matkul.objects.all()
    if request.method=="POST":
        form = FormMatkul(request.POST)
        if form.is_valid():
            simpan = form.save()
            simpan.save()
            form = FormMatkul()

    else:
        form = FormMatkul()

    
    context = {'form':form, 'daftar':daftar}

    return render (request, 'tambahmatkul.html', context)

def ikut_kegiatan(request):
    if request.method=="POST":
        form = FormPeserta(request.POST)
        if form.is_valid():
            simpan = form.save()
            simpan.save()
            form = FormPeserta()

    else:
        form = FormPeserta()

    context = {'form':form}

    return render(request, 'formulirkegiatan.html', context)

def tambah_kegiatan(request):
    daftar = Kegiatan.objects.all()
    if request.method=="POST":
        form = FormKegiatan(request.POST)
        if form.is_valid():
            simpan = form.save()
            simpan.save()
            form = FormKegiatan()

    else:
        form = FormKegiatan()

    context = {'form':form, 'daftar':daftar}

    return render(request, 'tambahkegiatan.html', context)

def daftar_matkul(request):
    daftar = Matkul.objects.all()
    return render(request, 'daftarmatkul.html', {'daftar':daftar})

def daftar_kegiatan(request):
    daftar = Peserta.objects.all()
    context = {'daftar':daftar}
    return render(request, 'lihatkegiatan.html', context)

def delete(request, pk):
    matkul = Matkul.objects.get(id=pk)
    context = {'matkul':matkul}
    if request.method=="POST":
        matkul.delete()
        return render(request, 'sudahhapus.html', context)
    
    return render(request, 'delete.html', context)

def deletekegiatan(request, pk):
    kegiatan = Kegiatan.objects.get(id=pk)
    context = {'kegiatan':kegiatan}
    if request.method=="POST":
        kegiatan.delete()
        return render(request, 'sudahhapuskegiatan.html', context)
    
    return render(request, 'deletekegiatan.html', context)

def about(request):
    return render(request, "About.html")

def story8(request):
    return render(request, "Story8.html")
    

def olahdata(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    ret = requests.get(url)
    hasil = json.loads(ret.content)
    return JsonResponse(hasil, safe=False)

def login(request):
    return render(request, "login.html")

def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('story3:login')
        

    else:
        form = UserCreationForm()

    return render (request, "signup.html", {'form':form})

story1/templates/story1.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'oldstyle.css' %}">
    <title>Profil Arik</title>
</head>
<body>

    <div class="container">

        {% include "base.html" %}
        
        <div class="header">
            <h1 class="nama">Athallah Rikza Ihsani</h1>
            <h2 class="title">Undergraduate Student at University of Indonesia</h2>
        </div>

        <div class="image"></div>

        <div class="content">
            <h3 class="subjudul">Profile Lengkap:</h3>
            <table class="profile">
            

                <tr>
                    <td>
                        Nama
                    </td>
                    <td>
                        :
                    </td>
                    <td class="data">
                        Athallah Rikza Ihsani
                    </td>
                </tr>

                <tr>
                    <td>
                        NPM
                    </td>
                    <td>
                        :
                    </td>
                    <td class="data">
                        1906353523
                    </td>
                </tr>

                <tr>
                    <td>
                        Angkatan
                    </td>
                    <td>
                        :
                    </td>
                    <td class="data">
                        2019
                    </td>
                </tr>

                <tr>
                    <td>
                        Hobi
                    </td>
                    <td>
                        :
                    </td>
                    <td class="data">
                        Membaca, main game, dan mendengarkan musik
                    </td>
                </tr>

                <tr>
                    <td>
                        Tempat Kuliah
                    </td>
                    <td>
                        :
                    </td>
                    <td class="data">
                        Universitas Indonesia
                    </td>
                </tr>

                <tr>
                    <td>Riwayat Pendidikan

                    </td>
                    <td>
                        :
                    </td>
                    
                    <td class="data">
                        <ul>
                            <li>Universitas Indonesia (2019 - Sekarang)</li>
                            <li>SMA Negeri 1 Kota Bogor (2016 - 2019)</li>
                            <li>SMP Negeri 4 Kota Bogor (2013 - 2016)</li>
                            <li>SD IT Dinamika (2007 - 2013)</li>
                        </ul>
                    </td>
                </tr>


            </table>
        </div>

        <div class="deskripsi">
            <h3 class="subjudul">Deskripsi Diri:</h3>
            <p class="isi">Nama saya adalah Athallah Rikza Ihsani, biasa dipanggil Arik.
                Saya merupakan mahasiswa Fakultas Ilmu Komputer Universitas Indonesia Jurusan 
                Sistem Informasi angkatan 2019. Saya memiliki ketertarikan di bidang Matematika dan Web 
                Development. Selama berkuliah di Fasilkom UI, saya pernah membuat berbagai macam proyek
                pemrogaman seperti membuat web static, membuat program sederhana, dan menganalisis data dari user. Saya memiliki cita-cita
                untuk bekerja pada sebuah startup multinasional sebagai project manager.

            </p>
        </div>

        <div class="MyContact">
          <h3 class="subjudul">Kontak:</h3>
          <table class="contact">

            <tr>
                <td>
                    ID Line
                </td>
                <td>
                    :
                </td>
                <td>
                    athallahrikza
                </td>
            </tr>

            <tr>
                <td>
                    Instagram
                </td>
                <td>
                    :
                </td>
                <td>
                    ArikIhsani
                </td>
            </tr>

            <tr>
                <td>
                    Whatsapp
                </td>
                <td>
                    :
                </td>
                <td>
                    087779080946
                </td>
            </tr>

          </table>
        </div>

        <div class="footer">
            <p class="copy">Copyright 2020. Athallah Rikza Ihsani. All rights reserved.</p>
        </div>

    </div>
    
</body>
</html>

story3/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="HandheldFriendly" content="true">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
</head>

<body>
    <div class="header">
        <h1 class="nama">Athallah Rikza Ihsani</h1>
        <h2 class="title">Undergraduate Student at University of Indonesia</h2>
    </div>

    <div class="navbar navbar-expand-sm navbar-dark bg-dark">
        <nav>
            
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarMenu">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarMenu">

                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="/" class="navbar-brand">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'story3:about' %}" class="nav-link">About</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'story3:story8' %}" class="nav-link">Story 8</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'story3:Contact' %}" class="nav-link">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'story3:tambahmatkul' %}" class="nav-link">Tambah Matkul</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'story3:daftarmatkul' %}" class="nav-link">Daftar Matkul</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'story3:ikutkegiatan' %}" class="nav-link">Ikut Kegiatan</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'story3:daftarkegiatan' %}" class="nav-link">Daftar Kegiatan</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'story3:tambahkegiatan' %}" class="nav-link">Tambah Kegiatan Baru</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'story3:logout' %}" class="nav-link">Log Out</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{% url 'story3:login' %}" class="nav-link">Log In</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a href="{% url 'story3:signup' %}" class="nav-link">Sign Up</a>
                    </li>
                </ul>

            </div>

        </nav>
    </div>

   
</body>
</html>

story3/templates/base2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="HandheldFriendly" content="true">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
</head>

<body>
    <div class="header">
        <h1 class="nama">Athallah Rikza Ihsani</h1>
        <h2 class="title">Undergraduate Student at University of Indonesia</h2>
    </div>

    <div class="navbar navbar-expand-sm navbar-dark bg-dark">
        <nav>
            
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarMenu">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarMenu">

                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="/" class="navbar-brand">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'story3:about' %}" class="nav-link">About</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'story3:story8' %}" class="nav-link">Story 8</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'story3:Contact' %}" class="nav-link">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'story3:tambahmatkul' %}" class="nav-link">Tambah Matkul</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'story3:daftarmatkul' %}" class="nav-link">Daftar Matkul</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'story3:ikutkegiatan' %}" class="nav-link">Ikut Kegiatan</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'story3:daftarkegiatan' %}" class="nav-link">Daftar Kegiatan</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'story3:tambahkegiatan' %}" class="nav-link">Tambah Kegiatan Baru</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'story3:login' %}" class="nav-link">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'story3:signup' %}" class="nav-link">Sign Up</a>
                    </li>
                </ul>

            </div>

        </nav>
    </div>

   
</body>
</html>

story3/templates/delete.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="HandheldFriendly" content="true">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Profil Arik</title>
</head>
<body>

    <div class="container">
        
        {% include "base.html" %}
        <p>Are you sure you want to delete "{{matkul.nama}}"</p>
        <form action = "{% url 'story3:delete' matkul.id %}" method="POST"> 
            {% csrf_token %}
            <a href="{% url 'story3:tambahmatkul' %}">Cancel</a>
            <input type="submit" name="Confirm">
        </form>

        
       
        
        
        
    
            
   

        

        <div class="footer">
            <p class="copy">Copyright 2020. Athallah Rikza Ihsani. All rights reserved.</p>
        </div>

    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

story3/templates/deletekegiatan.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="HandheldFriendly" content="true">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Profil Arik</title>
</head>
<body>

    <div class="container">
        
        {% include "base.html" %}
        <p>Are you sure you want to delete "{{kegiatan.nama}}"</p>
        <form action = "{% url 'story3:deletekegiatan' kegiatan.id %}" method="POST"> 
            {% csrf_token %}
            <a href="{% url 'story3:tambahkegiatan' %}">Cancel</a>
            <input type="submit" name="Confirm">
        </form>

        
       
        
        
        
    
            
   

        

        <div class="footer">
            <p class="copy">Copyright 2020. Athallah Rikza Ihsani. All rights reserved.</p>
        </div>

    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

story3/templates/tambahkegiatan.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="HandheldFriendly" content="true">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Profil Arik</title>
</head>
<body>

    <div class="container">
        
        {% include "base.html" %}

        <div class="jarak">
            <h3>Formulir Tambah Kegiatan</h3>
        </div>
       
        <div class="formulir">
            <form method="POST"> {% csrf_token %}
                <table>
                    {{form.as_table}}
                </table>
            
            <button type="submit">save</button>
        </div>

        <div class="jarak">
            <h3>Hapus Kegiatan</h3>
        </div>

        <table class = "listmatkul">
            <tr>
                <th>Nama Kegiatan</th>
                <th>Actions</th>
            </tr>
            {% for kegiatan in daftar %}
            <tr>
                <td>{{kegiatan.nama}}</td>
                <td><a class="btn btn-danger" href="{% url 'story3:deletekegiatan' kegiatan.id %}">Delete</a></td>
            </tr>
            {% endfor %}
        </table>


        
        
    
            
   

        

        <div class="footer">
            <p class="copy">Copyright 2020. Athallah Rikza Ihsani. All rights reserved.</p>
        </div>

    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

story3/templates/tambahmatkul.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="HandheldFriendly" content="true">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Profil Arik</title>
</head>
<body>

    <div class="container">
        
        {% include "base.html" %}

        <div class="jarak">
            <h3>Formulir Tambah Matkul</h3>
        </div>
       
        <div class="formulir">
            <form method="POST"> {% csrf_token %}
            <table>
                {{form.as_table}}
            </table>
                
            
            <button type="submit">save</button>
        </div>

        <div class="daftarmatkul">
            
            <div class="jarak">
                <h3>Hapus Matkul</h3>
            </div>
            

           <table class="listmatkul">
            <tr>
                <th>Nama Mata Kuliah</th>
                <th>Dosen</th>
                <th>Jumlah SKS</th>
                <th>Deskripsi Mata Kuliah</th>
                <th>Tahun Ajaran</th>
                <th>Ruang Kelas</th>
                <th>Actions</th>
            </tr>
            {% for matkul in daftar %}
            <tr>
                
                <td>{{matkul.nama}}</td>
                <td>{{matkul.dosen}}</td>
                <td>{{matkul.sks}}</td>
                <td>{{matkul.deskripsi}}</td>
                <td>{{matkul.tahun}}</td>
                <td>{{matkul.ruangan}}</td>
                <td><a class="btn btn-danger" href="{% url 'story3:delete' matkul.id %}">Delete</a></td>
                {% endfor %}
            </tr>
           
           </table>
        </div>
        
        
    
            
   

        

        <div class="footer">
            <p class="copy">Copyright 2020. Athallah Rikza Ihsani. All rights reserved.</p>
        </div>

    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>